### ISSUE TITLE
Error when downloading twitter video 

### ISSUE THREAD

**Issue by joaopinto24** [tegnatiek/viewdeo_help#2]
Attempting to download any twitter video with any method fails:
![Screenshot_20230519-113232_Chrome](https://github.com/njdwklopper/viewdeo_help/assets/132157779/162cec11-e369-4345-9c60-7dc76f27ede6)
API error:
{"errors":[{"code":215,"message":"Bad Authentication data."}]}
My guess woul be related to twitter blue having more API access

**Comment by jonathanklopper** [comment]
Sorry, App is now removed, and won't work ever again.
Twitter and reddit want exorbitant amounts of money for using their APIs.
